---
application:
  name: "wizz-cms"
  project: "wizz-cms"
  organization: "QoveryCommunity"
  storage:
  - name: "local"
    size: "5GB"
    type: "ssd"
    mount_point: "/mnt/local"
databases:
- type: "POSTGRESQL"
  name: "wizz-redis"
  version: "12"
routers:
- name: "main-wizz-cms"
  routes:
  - application_name: "wizz-cms"
    paths:
    - "/*"
